/******************************************************************************
 * lcd_font.h — 5x7 monospace ASCII font table (32..126, ~480 bytes).
 * Replaces the original 47-case switch in LCD_GlyphRow. Now supports full
 * printable ASCII including lowercase letters.
 *
 * Each glyph is 5 bytes wide × 7 rows tall, stored row-major: glyph[c-32][r].
 * Bit 4..0 = left..right; a set bit means the foreground color.
 ******************************************************************************/

#ifndef LCD_FONT_H_
#define LCD_FONT_H_

#include <stdint.h>

#define LCD_FONT_FIRST_CHAR ((char)0x20)  /* space = 32 */
#define LCD_FONT_LAST_CHAR  ((char)0x7E)  /* ~   = 126 */
#define LCD_FONT_COUNT      95U
#define LCD_FONT_GLYPH_W    5U            /* data width (bytes per row) */
#define LCD_FONT_GLYPH_H    7U            /* rows (not counting empty bottom row) */

/* Declared extern so multiple TUs can share. Generated by a compact
 * bit-to-byte encoding from the original 47-case switch, extended to 95 chars. */
extern const uint8_t lcd_font_5x7[LCD_FONT_COUNT][LCD_FONT_GLYPH_H];

#endif /* LCD_FONT_H_ */
