function result = build_pmsm_svpwm_model(varargin)
%BUILD_PMSM_SVPWM_MODEL Build and optionally simulate a dq PMSM FOC model.

varargin = cellfun(@convertStringsToChars, varargin, "UniformOutput", false);

parser = inputParser;
addParameter(parser, "OpenModel", true, @(value) islogical(value) && isscalar(value));
addParameter(parser, "RunSimulation", true, @(value) islogical(value) && isscalar(value));
parse(parser, varargin{:});

openModel = parser.Results.OpenModel;
runSimulation = parser.Results.RunSimulation;

projectDir = fileparts(mfilename("fullpath"));
modelName = "pmsm_dq_svpwm_cascade";
modelFile = fullfile(projectDir, modelName + ".slx");
plotFile = fullfile(projectDir, "pmsm_step_response.png");
figFile = fullfile(projectDir, "pmsm_step_response.fig");

params = getDefaultParameters();

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

if isfile(modelFile)
    delete(modelFile);
end

load_system("simulink");
new_system(modelName);

try
    configureModel(modelName, params);
    addModelBlocks(modelName, params);
    save_system(modelName, modelFile);

    if openModel
        open_system(modelName);
    end

    simOut = [];
    if runSimulation
        simOut = sim(modelName, "ReturnWorkspaceOutputs", "on");
        createStepResponsePlot(simOut, plotFile, figFile);
    end

    result = struct( ...
        "modelName", modelName, ...
        "modelFile", modelFile, ...
        "plotFile", plotFile, ...
        "figureFile", figFile, ...
        "params", params, ...
        "simOut", simOut);
catch errorInfo
    closeUnsavedModel(modelName);
    rethrow(errorInfo);
end
end

function params = getDefaultParameters()
params = struct();

params.Vdc = 36;
params.Ts = 5e-5;
params.StopTime = 4.0;
params.StepTime = 0.02;
params.PositionStep = 1.0;
params.LoadStepTime = 1.8;
params.LoadTorqueInitial = 0;

params.Rs = 0.6;
params.Ld = 0.82e-3;
params.Lq = 0.82e-3;
params.PolePairs = 14;
params.KvRpmPerVolt = 6.71;
params.MaxSpeedRpm = 1500;
params.KvAssumption = "raw user value; PsiF is estimated from Vdc and MaxSpeedRpm";
params.PsiF = voltageLimitedFluxLinkage( ...
    params.Vdc, params.MaxSpeedRpm, params.PolePairs);
params.Kt = 1.5 * params.PolePairs * params.PsiF;
params.GearStage1Ratio = 3.71428571428;
params.GearStage2Ratio = 14;
params.GearTotalRatio = params.GearStage1Ratio * params.GearStage2Ratio;
params.GearEfficiency = 1.0;
params.OutputMaxSpeedRpm = params.MaxSpeedRpm / params.GearTotalRatio;
params.RatedTorqueMotor = 0.7;
params.StallTorqueMotor = 2.2;
params.RatedTorqueOutput = params.RatedTorqueMotor * params.GearTotalRatio * params.GearEfficiency;
params.StallTorqueOutput = params.StallTorqueMotor * params.GearTotalRatio * params.GearEfficiency;
params.LoadTorqueStallFraction = 0.9;
params.LoadTorqueFinal = params.LoadTorqueStallFraction * params.StallTorqueOutput;
params.RatedCurrentFromTorque = params.RatedTorqueMotor / params.Kt;
params.StallCurrentFromTorque = params.StallTorqueMotor / params.Kt;
params.J = 8e-5;
params.B = 1e-4;

params.RatedCurrent = 3.8;
params.PeakCurrent = 19.5;
params.IdRef = 0;
params.IqLimit = min(params.PeakCurrent, params.StallCurrentFromTorque);
params.OmegaLimit = params.OutputMaxSpeedRpm * 2 * pi / 60;
params.VoltageLimit = params.Vdc / sqrt(3);

params.KpPosition = 2;
params.KiPosition = 0;
params.KpSpeed = 0.08;
params.KiSpeed = 1.0;

currentBandwidth = 1500;
params.KpCurrent = params.Ld * currentBandwidth;
params.KiCurrent = params.Rs * currentBandwidth;
end

function psiF = voltageLimitedFluxLinkage(vdc, maxSpeedRpm, polePairs)
maxMechanicalSpeed = maxSpeedRpm * 2 * pi / 60;
voltageLimit = vdc / sqrt(3);
psiF = voltageLimit / (polePairs * maxMechanicalSpeed);
end

function configureModel(modelName, params)
set_param(modelName, ...
    "StopTime", num2str(params.StopTime), ...
    "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", num2str(params.Ts), ...
    "ReturnWorkspaceOutputs", "on", ...
    "SignalLogging", "on", ...
    "SaveOutput", "off");

modelWorkspace = get_param(modelName, "ModelWorkspace");
assignin(modelWorkspace, "pmsm", params);
end

function addModelBlocks(modelName, params)
thetaStepBlock = modelName + "/theta_ref_step";
loadStepBlock = modelName + "/load_torque_step";
plantBlock = modelName + "/Cascaded PI SVPWM PMSM";

add_block("simulink/Sources/Step", thetaStepBlock, ...
    "Time", num2str(params.StepTime), ...
    "Before", "0", ...
    "After", num2str(params.PositionStep), ...
    "SampleTime", num2str(params.Ts), ...
    "Position", [50 90 95 120]);

add_block("simulink/Sources/Step", loadStepBlock, ...
    "Time", num2str(params.LoadStepTime), ...
    "Before", num2str(params.LoadTorqueInitial), ...
    "After", num2str(params.LoadTorqueFinal), ...
    "SampleTime", num2str(params.Ts), ...
    "Position", [50 185 95 215]);

add_block("simulink/User-Defined Functions/MATLAB Function", plantBlock, ...
    "Position", [180 45 455 290]);
setMatlabFunctionScript(plantBlock, params);

set_param(modelName, "SimulationCommand", "update");

add_line(modelName, "theta_ref_step/1", "Cascaded PI SVPWM PMSM/1", ...
    "autorouting", "on");
add_line(modelName, "load_torque_step/1", "Cascaded PI SVPWM PMSM/2", ...
    "autorouting", "on");

signalNames = { ...
    "iq", ...
    "omega_rpm", ...
    "theta_m", ...
    "omega_stage1_rpm", ...
    "theta_stage1", ...
    "omega_out_rpm", ...
    "theta_out", ...
    "id", ...
    "iq_ref", ...
    "omega_ref_rpm", ...
    "vd", ...
    "vq", ...
    "duty_a", ...
    "duty_b", ...
    "duty_c", ...
    "load_torque", ...
    "load_torque_motor", ...
    "torque_e", ...
    "torque_motor", ...
    "torque_stage1", ...
    "torque_output"};

topY = 30;
verticalSpacing = 42;
for idx = 1:numel(signalNames)
    blockName = signalNames{idx};
    sinkBlock = modelName + "/" + blockName;
    yPosition = topY + (idx - 1) * verticalSpacing;

    add_block("simulink/Sinks/To Workspace", sinkBlock, ...
        "VariableName", blockName, ...
        "SaveFormat", "Timeseries", ...
        "Position", [610 yPosition 700 yPosition + 28]);

    add_line(modelName, ...
        "Cascaded PI SVPWM PMSM/" + idx, ...
        blockName + "/1", ...
        "autorouting", "on");
end

annotationText = sprintf([ ...
    'Surface PMSM dq model with cascaded position, speed, and current PI loops\n', ...
    'SVPWM common-mode injection, Vdc = %.0f V, voltage vector limit = Vdc/sqrt(3)\n', ...
    'Gearbox: 1/%.11g then 1/%.0f, total reduction = 1/%.2f\n', ...
    'Load torque step: %.4f N*m at %.3f s'], ...
    params.Vdc, params.GearStage1Ratio, params.GearStage2Ratio, ...
    params.GearTotalRatio, params.LoadTorqueFinal, params.LoadStepTime);
note = Simulink.Annotation(modelName, annotationText);
note.Position = [50 345 620 400];
end

function setMatlabFunctionScript(blockPath, params)
chart = sfroot().find("-isa", "Stateflow.EMChart", "Path", blockPath);
if isempty(chart)
    error("PMSM:MissingMatlabFunctionChart", ...
        "Could not locate MATLAB Function chart at %s.", blockPath);
end

chart.Script = makeControllerPlantScript(params);
end

function script = makeControllerPlantScript(params)
num = @(value) sprintf("%.17g", value);

lines = { ...
"function [iq, omega_rpm, theta_m, omega_stage1_rpm, theta_stage1, omega_out_rpm, theta_out, id, iq_ref, omega_ref_rpm, vd, vq, duty_a, duty_b, duty_c, load_torque_out, load_torque_motor, torque_e, torque_motor, torque_stage1, torque_output] = foc_step(theta_ref, load_torque)", ...
"%#codegen", ...
"persistent id_state iq_state omega_state theta_state int_pos int_speed int_d int_q", ...
"if isempty(id_state)", ...
"    id_state = 0;", ...
"    iq_state = 0;", ...
"    omega_state = 0;", ...
"    theta_state = 0;", ...
"    int_pos = 0;", ...
"    int_speed = 0;", ...
"    int_d = 0;", ...
"    int_q = 0;", ...
"end", ...
"", ...
"Ts = " + num(params.Ts) + ";", ...
"Vdc = " + num(params.Vdc) + ";", ...
"Rs = " + num(params.Rs) + ";", ...
"Ld = " + num(params.Ld) + ";", ...
"Lq = " + num(params.Lq) + ";", ...
"psi_f = " + num(params.PsiF) + ";", ...
"pole_pairs = " + num(params.PolePairs) + ";", ...
"J = " + num(params.J) + ";", ...
"B = " + num(params.B) + ";", ...
"max_omega_motor = " + num(params.MaxSpeedRpm * 2 * pi / 60) + ";", ...
"gear_stage1 = " + num(params.GearStage1Ratio) + ";", ...
"gear_total = " + num(params.GearTotalRatio) + ";", ...
"gear_efficiency = " + num(params.GearEfficiency) + ";", ...
"id_ref = " + num(params.IdRef) + ";", ...
"iq_limit = " + num(params.IqLimit) + ";", ...
"phase_current_limit = " + num(params.PeakCurrent) + ";", ...
"omega_limit = " + num(params.OmegaLimit) + ";", ...
"voltage_limit = Vdc / sqrt(3);", ...
"kp_pos = " + num(params.KpPosition) + ";", ...
"ki_pos = " + num(params.KiPosition) + ";", ...
"kp_speed = " + num(params.KpSpeed) + ";", ...
"ki_speed = " + num(params.KiSpeed) + ";", ...
"kp_current = " + num(params.KpCurrent) + ";", ...
"ki_current = " + num(params.KiCurrent) + ";", ...
"", ...
"theta_out_state = theta_state / gear_total;", ...
"omega_out_state = omega_state / gear_total;", ...
"theta_error = theta_ref - theta_out_state;", ...
"[omega_ref, int_pos] = pi_limit(theta_error, int_pos, kp_pos, ki_pos, Ts, -omega_limit, omega_limit);", ...
"", ...
"speed_error = omega_ref - omega_out_state;", ...
"[iq_ref, int_speed] = pi_limit(speed_error, int_speed, kp_speed, ki_speed, Ts, -iq_limit, iq_limit);", ...
"", ...
"omega_e = pole_pairs * omega_state;", ...
"id_error = id_ref - id_state;", ...
"iq_error = iq_ref - iq_state;", ...
"", ...
"[vd_pi, int_d] = pi_limit(id_error, int_d, kp_current, ki_current, Ts, -voltage_limit, voltage_limit);", ...
"[vq_pi, int_q] = pi_limit(iq_error, int_q, kp_current, ki_current, Ts, -voltage_limit, voltage_limit);", ...
"", ...
"vd_ff = -omega_e * Lq * iq_state;", ...
"vq_ff = omega_e * (Ld * id_state + psi_f);", ...
"vd_cmd = vd_pi + vd_ff;", ...
"vq_cmd = vq_pi + vq_ff;", ...
"[vd, vq] = limit_vector(vd_cmd, vq_cmd, voltage_limit);", ...
"", ...
"did = (vd - Rs * id_state + omega_e * Lq * iq_state) / Ld;", ...
"diq = (vq - Rs * iq_state - omega_e * (Ld * id_state + psi_f)) / Lq;", ...
"torque_e = 1.5 * pole_pairs * (psi_f * iq_state + (Ld - Lq) * id_state * iq_state);", ...
"load_torque_motor = load_torque / (gear_total * gear_efficiency);", ...
"domega = (torque_e - load_torque_motor - B * omega_state) / J;", ...
"", ...
"id_state = saturate(id_state + Ts * did, -phase_current_limit, phase_current_limit);", ...
"iq_state = saturate(iq_state + Ts * diq, -iq_limit, iq_limit);", ...
"omega_state = saturate(omega_state + Ts * domega, -max_omega_motor, max_omega_motor);", ...
"theta_state = theta_state + Ts * omega_state;", ...
"", ...
"[duty_a, duty_b, duty_c] = svpwm_duty(vd, vq, theta_state, pole_pairs, Vdc);", ...
"", ...
"id = id_state;", ...
"iq = iq_state;", ...
"theta_m = theta_state;", ...
"omega_rpm = omega_state * 60 / (2 * pi);", ...
"theta_stage1 = theta_state / gear_stage1;", ...
"omega_stage1_rpm = omega_rpm / gear_stage1;", ...
"theta_out = theta_state / gear_total;", ...
"omega_out_rpm = omega_rpm / gear_total;", ...
"omega_ref_rpm = omega_ref * 60 / (2 * pi);", ...
"load_torque_out = load_torque;", ...
"torque_motor = torque_e;", ...
"torque_stage1 = torque_motor * gear_stage1 * gear_efficiency;", ...
"torque_output = torque_motor * gear_total * gear_efficiency;", ...
"end", ...
"", ...
"function [u, integrator] = pi_limit(error, integrator, kp, ki, Ts, min_value, max_value)", ...
"candidate_integrator = integrator + ki * Ts * error;", ...
"raw = kp * error + candidate_integrator;", ...
"u_candidate = saturate(raw, min_value, max_value);", ...
"if raw == u_candidate || (raw > max_value && error < 0) || (raw < min_value && error > 0)", ...
"    integrator = candidate_integrator;", ...
"end", ...
"u = saturate(kp * error + integrator, min_value, max_value);", ...
"end", ...
"", ...
"function [d_axis, q_axis] = limit_vector(d_axis, q_axis, limit_value)", ...
"magnitude = sqrt(d_axis * d_axis + q_axis * q_axis);", ...
"if magnitude > limit_value && magnitude > 0", ...
"    scale = limit_value / magnitude;", ...
"    d_axis = d_axis * scale;", ...
"    q_axis = q_axis * scale;", ...
"end", ...
"end", ...
"", ...
"function value = saturate(value, min_value, max_value)", ...
"if value > max_value", ...
"    value = max_value;", ...
"elseif value < min_value", ...
"    value = min_value;", ...
"end", ...
"end", ...
"", ...
"function [duty_a, duty_b, duty_c] = svpwm_duty(vd, vq, theta_m, pole_pairs, Vdc)", ...
"theta_e = pole_pairs * theta_m;", ...
"cos_e = cos(theta_e);", ...
"sin_e = sin(theta_e);", ...
"v_alpha = cos_e * vd - sin_e * vq;", ...
"v_beta = sin_e * vd + cos_e * vq;", ...
"", ...
"v_a = v_alpha;", ...
"v_b = -0.5 * v_alpha + sqrt(3) * 0.5 * v_beta;", ...
"v_c = -0.5 * v_alpha - sqrt(3) * 0.5 * v_beta;", ...
"", ...
"v_max = max(v_a, max(v_b, v_c));", ...
"v_min = min(v_a, min(v_b, v_c));", ...
"v_zero = -0.5 * (v_max + v_min);", ...
"", ...
"duty_a = saturate(0.5 + (v_a + v_zero) / Vdc, 0, 1);", ...
"duty_b = saturate(0.5 + (v_b + v_zero) / Vdc, 0, 1);", ...
"duty_c = saturate(0.5 + (v_c + v_zero) / Vdc, 0, 1);", ...
"end"};

lines = cellfun(@char, lines, "UniformOutput", false);
script = strjoin(lines, newline);
end

function createStepResponsePlot(simOut, plotFile, figFile)
iq = simOut.get("iq");
omegaMotorRpm = simOut.get("omega_rpm");
omegaStage1Rpm = simOut.get("omega_stage1_rpm");
omegaOutputRpm = simOut.get("omega_out_rpm");
thetaM = simOut.get("theta_out");
loadTorque = simOut.get("load_torque");
torqueMotor = simOut.get("torque_motor");
torqueStage1 = simOut.get("torque_stage1");
torqueOutput = simOut.get("torque_output");

fig = figure("Name", "PMSM dq SVPWM step response", "Color", "w");
layout = tiledlayout(fig, 5, 1, "TileSpacing", "compact", "Padding", "compact");

nexttile(layout);
plot(iq.Time, iq.Data, "LineWidth", 1.2);
grid on;
ylabel("i_q (A)");
title("PMSM Output-Shaft Position Step Response");

nexttile(layout);
plot(omegaMotorRpm.Time, omegaMotorRpm.Data, "LineWidth", 1.2);
hold on;
plot(omegaStage1Rpm.Time, omegaStage1Rpm.Data, "--", "LineWidth", 1.1);
plot(omegaOutputRpm.Time, omegaOutputRpm.Data, ":", "LineWidth", 1.4);
hold off;
grid on;
ylabel("Speed (rpm)");
legend(["Motor", "After stage 1", "Output"], "Location", "best");

nexttile(layout);
plot(thetaM.Time, thetaM.Data, "LineWidth", 1.2);
grid on;
ylabel("Position (rad)");

nexttile(layout);
plot(torqueMotor.Time, torqueMotor.Data, "LineWidth", 1.2);
grid on;
ylabel("Motor T (N*m)");

nexttile(layout);
plot(torqueStage1.Time, torqueStage1.Data, "--", "LineWidth", 1.1);
hold on;
plot(torqueOutput.Time, torqueOutput.Data, "LineWidth", 1.2);
plot(loadTorque.Time, loadTorque.Data, ":", "LineWidth", 1.4);
hold off;
grid on;
ylabel("Gear T (N*m)");
legend(["After stage 1", "Output", "Output load"], "Location", "best");
xlabel("Time (s)");

axesHandles = findall(fig, "Type", "Axes");
for idx = 1:numel(axesHandles)
    axesHandles(idx).Toolbar.Visible = "off";
end

exportgraphics(fig, plotFile, "Resolution", 160);
savefig(fig, figFile);
end

function closeUnsavedModel(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
